
#MySQL
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/libreriaspring?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
#Hibernate
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
              dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    #Para que thymeleaf no guarde datos en cache
    thymeleaf:
        cache: false

    